.apex/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/ItemImageTest.cls
@IsTest
private class ItemImageTest {
	@IsTest
	static void TestImages(){
		Item__c it1 = new Item__c(Name='B1', Price__c = 10, Description__c ='Something');
		Item__c it2 = new Item__c(Name='B2', Price__c = 20, Description__c ='Something');
		insert new List<Item__c>{ it1, it2 };
		UnsplashService.fakeUrl = 'https://test.com/fake.jpg';


		Test.startTest();
		GetImageItem.ItemsWithImages();
		Test.stopTest();
		Item__c It = [SELECT Id, Image__c FROM Item__c WHERE Name='B1'];
		System.assertEquals('https://test.com/fake.jpg',It.Image__c);
	}
}