.apex/src/objects/Item__c.object
<CustomObject>
    <fields>
        <fullName>Image__c</fullName>
        <label>Image</label>
        <required>true</required>
        <type>Url</type>
    </fields>
    <label>Item</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

.apex/src/classes/GetImageItem.cls
public class GetImageItem {
	@AuraEnabled
	public static void ItemsWithImages() {
		List<Item__c> itemsToUpdate = [SELECT Id, Name, Image__c FROM Item__c WHERE Image__c = NULL];

		List<Item__c> updatedItems = new List<Item__c>();

		for (Item__c it : itemsToUpdate) {
			String imageUrl = UnsplashService.getImageUrl(it.Name);

			if (imageUrl != null) {
				it.Image__c = imageUrl;
				updatedItems.add(it);
			}
		}
		if (!updatedItems.isEmpty()) {
			update updatedItems;
		}
	}
}