src/objects/Purchase__c.object
<CustomObject>
    <fields>
        <fullName>GrandTotal__c</fullName>
        <label>GrandTotal</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalNumber__c</fullName>
        <label>TotalItems</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Purchase</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchases</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/PurchaseLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>PurchaseId__c</fullName>
        <label>PurchaseId</label>
        <referenceTo>Purchase__c</referenceTo>
        <relationshipLabel>PurchaseLines</relationshipLabel>
        <relationshipName>PurchaseLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>PurchaseLine</label>
    <nameField>
        <displayFormat>{0000}</displayFormat>
        <label>Line Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PurchaseLines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

.apex/src/objects/PurchaseLine__c.object
    <fields>
        <fullName>TotalCost__c</fullName>
        <formula>UnitCost__c * Amount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>TotalCost</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>

src/classes/PurchaseLineHandler.cls
public class PurchaseLineHandler {
	public static void recalculatePurchases(Set<Id> purchaseIds) {


		List<AggregateResult> results = [
				SELECT PurchaseId__c pId,
				SUM(Amount__c) totalItems,
				SUM(TotalCost__c) grandTotal
				FROM PurchaseLine__c
				WHERE PurchaseID__c IN :purchaseIds
				GROUP BY PurchaseId__c
		];

		Map<Id, Purchase__c> toUpdate = new Map<Id, Purchase__c>();
		for (AggregateResult ar : results) {
			Id purchaseId = (Id) ar.get('pId');
			Purchase__c p = new Purchase__c(
					Id = purchaseId,
					TotalNumber__c = (Decimal) ar.get('totalItems'),
					GrandTotal__c = (Decimal) ar.get('grandTotal')
			);
			toUpdate.put(p.Id, p);
		}

		if (!toUpdate.isEmpty()) {
			update toUpdate.values();
		}
	}
}